routes/web.php
Route::get('contact-us', ['as' => 'contact_us_page', 'uses'=>'HomeController@contactUs']);
Route::post('contact-us', ['uses'=>'HomeController@contactUsPost']);

Route::get('page/{slug}', ['as' => 'single_page', 'uses'=>'PostController@showPage']);


Route::get('blog', ['as' => 'blog', 'uses'=>'PostController@blogIndex']);
Route::get('blog/{slug}', ['as' => 'blog_single', 'uses'=>'PostController@blogSingle']);
Route::get('blog/author/{id}', ['as' => 'author_blog_posts', 'uses'=>'PostController@authorPosts']);


Route::get('listing', ['as' => 'listing', 'uses'=>'AdsController@listing']);
Route::get('ad/{slug}', ['as' => 'single_ad', 'uses'=>'AdsController@singleAd']);
Route::get('embedded/{slug}', ['as' => 'embedded_ad', 'uses'=>'AdsController@embeddedAd']);

Route::post('save-ad-as-favorite', ['as' => 'save_ad_as_favorite', 'uses'=>'UserController@saveAdAsFavorite']);
Route::post('report-post', ['as' => 'report_ads_pos', 'uses'=>'AdsController@reportAds']);
Route::post('reply-by-email', ['as' => 'reply_by_email_post', 'uses'=>'UserController@replyByEmailPost']);

// Password reset routes...
Route::post('send-password-reset-link', ['as' => 'send_reset_link', 'uses'=>'UserController@postEmailResetPassword']);
Route::get('password/reset/{token}', ['as' => 'password_reset_url', 'uses' => 'UserController@passwordResetForm']);
Route::post('password/reset/{token}', [ 'uses' => 'UserController@passwordResetPost']);




//Auth::routes();

// Password reset routes...
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
//Route::post('password/reset', 'Auth\ResetPasswordController@postReset')->name('password.reset');


Route::post('get-sub-category-by-category', ['as'=>'get_sub_category_by_category', 'uses' => 'AdsController@getSubCategoryByCategory']);
Route::post('get-brand-by-category', ['as'=>'get_brand_by_category', 'uses' => 'AdsController@getBrandByCategory']);
Route::post('get-category-info', ['as'=>'get_category_info', 'uses' => 'AdsController@getParentCategoryInfo']);
Route::post('get-state-by-country', ['as'=>'get_state_by_country', 'uses' => 'AdsController@getStateByCountry']);
Route::post('get-city-by-state', ['as'=>'get_city_by_state', 'uses' => 'AdsController@getCityByState']);
Route::post('switch/product-view', ['as'=>'switch_grid_list_view', 'uses' => 'AdsController@switchGridListView']);



Route::group(['prefix'=>'login'], function(){
    //Native login route
    Route::get('/', ['as' => 'login', 'uses'=>'UserController@login']);
    Route::post('/', ['uses'=>'UserController@loginPost']);

    //Social login route

    Route::get('facebook', ['as' => 'facebook_redirect', 'uses'=>'SocialLogin@redirectFacebook']);
    Route::get('facebook-callback', ['as' => 'facebook_callback', 'uses'=>'SocialLogin@callbackFacebook']);

    Route::get('google', ['as' => 'google_redirect', 'uses'=>'SocialLogin@redirectGoogle']);
    Route::get('google-callback', ['as' => 'google_callback', 'uses'=>'SocialLogin@callbackGoogle']);

});

Route::resource('user', 'UserController');

//Dashboard Route
Route::group(['prefix'=>'dashboard', 'middleware' => 'dashboard'], function(){
    Route::get('/', ['as'=>'dashboard', 'uses' => 'DashboardController@dashboard']);

    Route::group(['middleware'=>'only_admin_access'], function(){
        Route::group(['prefix'=>'settings'], function(){
            Route::get('theme-settings', ['as'=>'theme_settings', 'uses' => 'SettingsController@ThemeSettings']);
            Route::get('modern-theme-settings', ['as'=>'modern_theme_settings', 'uses' => 'SettingsController@modernThemeSettings']);
            Route::get('social-url-settings', ['as'=>'social_url_settings', 'uses' => 'SettingsController@SocialUrlSettings']);
            Route::get('general', ['as'=>'general_settings', 'uses' => 'SettingsController@GeneralSettings']);
            Route::get('payments', ['as'=>'payment_settings', 'uses' => 'SettingsController@PaymentSettings']);
            Route::get('ad', ['as'=>'ad_settings', 'uses' => 'SettingsController@AdSettings']);
            Route::get('languages', ['as'=>'language_settings', 'uses' => 'LanguageController@index']);
            Route::post('languages', ['uses' => 'LanguageController@store']);
            Route::post('languages-delete', ['as'=>'delete_language', 'uses' => 'LanguageController@destroy']);

            Route::get('storage', ['as'=>'file_storage_settings', 'uses' => 'SettingsController@StorageSettings']);
            Route::get('social', ['as'=>'social_settings', 'uses' => 'SettingsController@SocialSettings']);
            Route::get('blog', ['as'=>'blog_settings', 'uses' => 'SettingsController@BlogSettings']);
            Route::get('other', ['as'=>'other_settings', 'uses' => 'SettingsController@OtherSettings']);
            Route::post('other', ['as'=>'other_settings', 'uses' => 'SettingsController@OtherSettingsPost']);

            //Save settings / options
            Route::post('save-settings', ['as'=>'save_settings', 'uses' => 'SettingsController@update']);
            Route::get('monetization', ['as'=>'monetization', 'uses' => 'SettingsController@monetization']);
        });

        Route::group(['prefix'=>'location'], function(){
            Route::get('country', ['as'=>'country_list', 'uses' => 'LocationController@countries']);
            Route::get('country-data', ['as'=>'get_countries_data', 'uses' => 'LocationController@getCountriesData']);
            Route::get('states', ['as'=>'state_list', 'uses' => 'LocationController@stateList']);
            Route::post('states', [ 'uses' => 'LocationController@saveState']);
            Route::get('states/{id}/edit', ['as'=>'edit_state', 'uses' => 'LocationController@stateEdit']);
            Route::post('states/{id}/edit', ['uses' => 'LocationController@stateEditPost']);
            Route::post('states/delete', ['as'=>'delete_state', 'uses' => 'LocationController@stateDestroy']);
            Route::get('state-data', ['as'=>'get_state_data', 'uses' => 'LocationController@getStatesData']);
            Route::get('cities', ['as'=>'city_list', 'uses' => 'LocationController@cityList']);
            Route::post('cities', ['uses' => 'LocationController@saveCity']);
            Route::get('city-data', ['as'=>'get_city_data', 'uses' => 'LocationController@getCityData']);

            Route::get('cities/{id}/edit', ['as'=>'edit_city', 'uses' => 'LocationController@cityEdit']);
            Route::post('cities/{id}/edit', ['uses' => 'LocationController@cityEditPost']);
            Route::post('city/delete', ['as'=>'delete_city', 'uses' => 'LocationController@cityDestroy']);
        });

        Route::group(['prefix'=>'categories'], function(){
            Route::get('/', ['as'=>'parent_categories', 'uses' => 'CategoriesController@index']);
            Route::post('/', ['uses' => 'CategoriesController@store']);

            Route::get('edit/{id}', ['as'=>'edit_categories', 'uses' => 'CategoriesController@edit']);
            Route::post('edit/{id}', ['uses' => 'CategoriesController@update']);

            Route::post('delete-categories', ['as'=>'delete_categories', 'uses' => 'CategoriesController@destroy']);
        });

        Route::group(['prefix'=>'distances'], function(){
            Route::get('/', ['as'=>'admin_brands', 'uses' => 'BrandsController@index']);
            Route::post('/', ['uses' => 'BrandsController@store']);
            Route::get('edit/{id}', ['as'=>'edit_brands', 'uses' => 'BrandsController@edit']);
            Route::post('edit/{id}', ['uses' => 'BrandsController@update']);
            Route::post('delete-distances', ['as'=>'delete_brands', 'uses' => 'BrandsController@destroy']);
        });

        Route::group(['prefix'=>'posts'], function(){
            Route::get('/', ['as'=>'posts', 'uses' => 'PostController@posts']);
            Route::get('data', ['as'=>'posts_data', 'uses' => 'PostController@postsData']);

            Route::get('create', ['as'=>'create_new_post', 'uses' => 'PostController@createPost']);
            Route::post('create', ['uses' => 'PostController@storePost']);
            Route::post('delete', ['as'=>'delete_post','uses' => 'PostController@destroyPost']);

            Route::get('edit/{slug}', ['as'=>'edit_post', 'uses' => 'PostController@editPost']);
            Route::post('edit/{slug}', ['uses' => 'PostController@updatePost']);
        });

        Route::group(['prefix'=>'pages'], function(){
            Route::get('/', ['as'=>'pages', 'uses' => 'PostController@index']);
            Route::get('data', ['as'=>'pages_data', 'uses' => 'PostController@pagesData']);

            Route::get('create', ['as'=>'create_new_page', 'uses' => 'PostController@create']);
            Route::post('create', ['uses' => 'PostController@store']);
            Route::post('delete', ['as'=>'delete_page','uses' => 'PostController@destroy']);

            Route::get('edit/{slug}', ['as'=>'edit_page', 'uses' => 'PostController@edit']);
            Route::post('edit/{slug}', ['uses' => 'PostController@updatePage']);
        });

        Route::group(['prefix'=>'slider'], function(){
            Route::get('/', ['as'=>'slider', 'uses' => 'SliderController@index']);
            Route::get('create', ['as'=>'create_slider', 'uses' => 'SliderController@create']);
            Route::post('create', ['uses' => 'SliderController@store']);
            Route::post('crop', ['as'=>'create_crop', 'uses' => 'SliderController@postCrop']);
            Route::post('delete', ['as'=>'delete_slider', 'uses' => 'SliderController@destroy']);
            Route::post('update-caption', ['as'=>'update_slider_caption', 'uses' => 'SliderController@update']);
        });

        Route::get('approved', ['as'=>'approved_ads', 'uses' => 'AdsController@index']);
        Route::get('pending', ['as'=>'admin_pending_ads', 'uses' => 'AdsController@adminPendingAds']);
        Route::get('blocked', ['as'=>'admin_blocked_ads', 'uses' => 'AdsController@adminBlockedAds']);

resources/views/theme/about-us.blade.php
@extends('layout.main')
@section('title') @if( ! empty($title)) {{ $title }} | @endif @parent @endsection
@section('main')
<div class="row mlr0">
   <div class="page_wrapper page-{{ $page->id }}">
      <div class="modern-top-intoduce-section banner">
         <div class="container">
            <div class="row">
               <div class="col-sm-12 col-lg-12">
                  <h2>About Us</h2>
               </div>
            </div>
         </div>
      </div>
      <div class="container">
         <div class="about_us clearfix">
            <div class="col-sm-6">
               <h6>Introduction</h6>
               <h2>Get Started with Property Lookout</h2>
               <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s.</p>
               <p>People are beginning to understand that. However, back over in reality some project schedules and budgets don&rsquo;t allow.</p>
               <div class="learn_more about_more"><a class="btn btn-primary" href="#">Read More</a></div>
            </div>
            <div class="col-sm-6"><img class="img-responsive" src="http://localhost/realestate/assets/img/about_us.jpg" /></div>
         </div>
      </div>
      <div class="company_work">
         <div class="container">
            <div class="row">
               <div class="col-md-3 col-xs-6">
                  <i class="fa fa-home" aria-hidden="true"></i>
                  <div class="col-text">
                     <h4>999</h4>
                     <h5>Complete Project</h5>
                  </div>
               </div>
               <div class="col-md-3 col-xs-6">
                  <i class="fa fa-key" aria-hidden="true"></i>
                  <div class="col-text">
                     <h4>720</h4>
                     <h5>Property Sold</h5>
                  </div>
               </div>
               <div class="col-md-3 col-xs-6">
                  <i class="fa fa-smile-o" aria-hidden="true"></i>
                  <div class="col-text">
                     <h4>450</h4>
                     <h5>Happy Clients</h5>
                  </div>
               </div>
               <div class="col-md-3 col-xs-6">
                  <i class="fa fa-trophy" aria-hidden="true"></i>
                  <div class="col-text">
                     <h4>120</h4>
                     <h5>Awards Win</h5>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="meet_agent">
         <div class="container">
            <h2>MEET OUR AGENT</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta est,<br />
               itaque inventore, eum, hic ullam quos sint dolore doloremque rerum enim?
            </p>
            <div class="row">
               <div class="col-md-3 col-sm-6">
                  <div class="agent-detail">
                     <a href="#"><img src="http://localhost/realestate/assets/img/agent-1.png" /></a>
                     <div class="detail">
                        <h5>Marcus</h5>
                        <span>Company Agent at Property Lookout</span>
                     </div>
                     <ul>
                        <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6">
                  <div class="agent-detail">
                     <a href="#"><img src="http://localhost/realestate/assets/img/agent-2.png" /></a>
                     <div class="detail">
                        <h5>Marcus</h5>
                        <span>Company Agent at Property Lookout</span>
                     </div>
                     <ul>
                        <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6">
                  <div class="agent-detail">
                     <a href="#"><img src="http://localhost/realestate/assets/img/agent-3.png" /></a>
                     <div class="detail">
                        <h5>Marcus</h5>
                        <span>Company Agent at Property Lookout</span>
                     </div>
                     <ul>
                        <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6">
                  <div class="agent-detail">
                     <a href="#"><img src="http://localhost/realestate/assets/img/agent-2.png" /></a>
                     <div class="detail">
                        <h5>Marcus</h5>
                        <span>Company Agent at Property Lookout</span>
                     </div>
                     <ul>
                        <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- {!! $page->post_content !!}  -->        
   </div>
</div>
@endsection
@section('page-js')
<script>
   @if(session('success'))
       toastr.success('{{ session('success') }}', '<?php echo trans('app.success') ?>', toastr_options);
   @endif
</script>
@endsection

resources/views/theme/agent-profile.blade.php
@extends('layout.main')
@section('title') @if( ! empty($title)) {{ $title }} | @endif @parent @endsection
@section('main')
<div class="row mlr0">
   <div class="page_wrapper page-{{ $page->id }}">
      <div class="modern-top-intoduce-section banner">
         <div class="container">
            <div class="row">
               <div class="col-sm-12 col-lg-12">
                  <h2>Agent Detail</h2>
               </div>
            </div>
         </div>
      </div>
      <div class="about_us single-agent_detail">
         <div class="container">
            <div class="row clearfix">
               <div class="col-sm-3 agent-avtar">
                  <div class="avtar"><img src="http://localhost/realestate/assets/img/marcus.png" /></div>
                  <ul class="agent_profiles">
                     <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                     <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                     <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                  </ul>
                  <div><a class="btn btn-primary contact-btn" href="#">Contact</a></div>
               </div>
               <div class="col-sm-5 agent-detail-manual">
                  <h2>Marcus Marrio</h2>
                  <span>Sale Assocaite - (Property Lookout)</span>
                  <ul>
                     <li><a href="callto:+60194526523">+60194526523</a></li>
                     <li><a href="mailto:marrio.sa@gmail.com">marrio.sa@gmail.com</a></li>
                     <li>Lot 4452, Taman Damansara, Kuching, Sarawak</li>
                     <li><a href="#">www.marcusmarrio.com.my</a></li>
                  </ul>
                  <table>
                     <tbody>
                        <tr>
                           <td>Gender:</td>
                           <td>Male</td>
                        </tr>
                        <tr>
                           <td>Country:</td>
                           <td>Malaysia</td>
                        </tr>
                        <tr>
                           <td>Company:</td>
                           <td>ABC Estate</td>
                        </tr>
                     </tbody>
                  </table>
               </div>
            </div>
            <h2>About Marcus Marrio</h2>
            <p>Dummy text is text that is used in the publishing industry or by web designers to occupy the space which will later be filled with &#39;real&#39; content. This is required when, for example, the final text is not yet available. Dummy text is also known as &#39;fill text&#39;. It is said that song composers of the past used dummy texts as lyrics when writing melodies in order to have a &#39;ready-made&#39; text to sing with the melody. Dummy texts have been in use by typesetters since the 16th century.</p>
            <p>Dummy text is text that is used in the publishing industry or by web designers to occupy the space which will later be filled with &#39;real&#39; content. This is required when, for example, the final text is not yet available. Dummy text is also known as &#39;fill text&#39;. It is said that song composers of the past used dummy texts as lyrics when writing melodies in order to have a &#39;ready-made&#39; text to sing with the melody. Dummy texts have been in use by typesetters since the 16th century.</p>
         </div>
      </div>
      <!-- {!! $page->post_content !!}  -->        
   </div>
</div>
@endsection
@section('page-js')
<script>
   @if(session('success'))
       toastr.success('{{ session('success') }}', '<?php echo trans('app.success') ?>', toastr_options);
   @endif
</script>
@endsection

resources/views/theme/error_404.blade.php
@extends('layout.main')
@section('title') @if( ! empty($title)) {{ $title }} | @endif @parent @endsection

@section('main')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="bg-white error-404-wrap">
                    <h1>
                        Oops!</h1>
                    <h2>
                        404 Not Found</h2>
                    <div class="error-details">
                        Sorry, an error has occured, Requested page not found!
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/theme/login.blade.php
@extends('layout.main')
@section('title') Log-In | @parent @endsection
@section('main')
<<<<<<< HEAD

    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 col-xs-12">

                <div class="login">
                    <h3 class="authTitle">Login or <a href="{{ route('user.create') }}">Sign up</a></h3>

                    @if(get_option('enable_social_login') == 1)


                        <div class="row row-sm-offset-3 socialButtons">

                            @if(get_option('enable_facebook_login') == 1)
                                <div class="col-xs-6">
                                    <a href="{{ route('facebook_redirect') }}" class="btn btn-lg btn-block btn-facebook">
                                        <i class="fa fa-facebook visible-xs"></i>
                                        <span class="hidden-xs"><i class="fa fa-facebook-square"></i> Facebook</span>
                                    </a>
                                </div>
                            @endif

                            @if(get_option('enable_google_login') == 1)
                                <div class="col-xs-6">
                                    <a href="{{ route('google_redirect') }}" class="btn btn-lg btn-block btn-google">
                                        <i class="fa fa-google-plus visible-xs"></i>
                                        <span class="hidden-xs"><i class="fa fa-google-plus-square"></i> Google+</span>
                                    </a>
                                </div>
                            @endif

                        </div>

                        <div class="row row-sm-offset-3 loginOr">
                            <div class="col-xs-12">
                                <hr class="hrOr">
                                <span class="spanOr">or</span>
                            </div>
                        </div>

                    @endif

                    <div class="row row-sm-offset-3">
                        <div class="col-xs-12">
                            {{ Form::open(['class'=> 'loginForm', 'autocomplete'=> 'off']) }}

                            <div class="input-group {{ $errors->has('email')? 'has-error':'' }}">
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                <input type="email" class="form-control" name="email" value="{{ old('email') }}" placeholder="email address">

                            </div>
                            {!! $errors->has('email')? '<p class="help-block">'.$errors->first('email').'</p>':'' !!}
                            <span class="help-block"></span>

                            <div class="input-group {{ $errors->has('password')? 'has-error':'' }}">
                                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                <input  type="password" class="form-control" name="password" placeholder="Password">
                            </div>
                            {!! $errors->has('password')? '<p class="help-block">'.$errors->first('password').'</p>':'' !!}

                            <span class="help-block"></span>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
                            {{ Form::close() }}
                        </div>
                    </div>
                    <div class="row row-sm-offset-3">
                        <div class="col-xs-12">
                            <div class="col-xs-12 col-sm-6">
                                <label class="checkbox">
                                    <input type="checkbox" value="remember-me">Remember Me
                                </label>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <p class="forgotPassword">
                                    <a href="#" data-toggle="modal" data-target="#forgotPasswordEmail"> @lang('app.forgot_password')</a>
                                </p>
                            </div>
                        </div>

                    </div>
                    <p class="new_register">Are you an agent wanting to join the platform?&nbsp;<a href="{{ route('user.create') }}">Register</a></p>
                </div>
=======
<div class="container">
   <div class="row">
      <div class="col-sm-6 col-sm-offset-3 col-xs-12">
         <div class="login">
            <h3 class="authTitle">Login or <a href="{{ route('user.create') }}">Sign up</a></h3>
            @if(get_option('enable_social_login') == 1)
            <div class="row row-sm-offset-3 socialButtons">
               @if(get_option('enable_facebook_login') == 1)
               <div class="col-xs-6">
                  <a href="{{ route('facebook_redirect') }}" class="btn btn-lg btn-block btn-facebook">
                  <i class="fa fa-facebook visible-xs"></i>
                  <span class="hidden-xs"><i class="fa fa-facebook-square"></i> Facebook</span>
                  </a>
               </div>
               @endif
               @if(get_option('enable_google_login') == 1)
               <div class="col-xs-6">
                  <a href="{{ route('google_redirect') }}" class="btn btn-lg btn-block btn-google">
                  <i class="fa fa-google-plus visible-xs"></i>
                  <span class="hidden-xs"><i class="fa fa-google-plus-square"></i> Google+</span>
                  </a>
               </div>
               @endif
>>>>>>> a676c9369ad63a676d00a05de1ac8137ef059953
            </div>
            <div class="row row-sm-offset-3 loginOr">
               <div class="col-xs-12">
                  <hr class="hrOr">
                  <span class="spanOr">or</span>
               </div>
            </div>
            @endif
            <div class="row row-sm-offset-3">
               <div class="col-xs-12">
                  {{ Form::open(['class'=> 'loginForm', 'autocomplete'=> 'off']) }}
                  <div class="input-group {{ $errors->has('email')? 'has-error':'' }}">
                     <span class="input-group-addon"><i class="fa fa-user"></i></span>
                     <input type="email" class="form-control" name="email" value="{{ old('email') }}" placeholder="email address">
                  </div>
                  {!! $errors->has('email')? '
                  <p class="help-block">'.$errors->first('email').'</p>
                  ':'' !!}
                  <span class="help-block"></span>
                  <div class="input-group {{ $errors->has('password')? 'has-error':'' }}">
                     <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                     <input  type="password" class="form-control" name="password" placeholder="Password">
                  </div>
                  {!! $errors->has('password')? '
                  <p class="help-block">'.$errors->first('password').'</p>
                  ':'' !!}
                  <span class="help-block"></span>
                  <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
                  {{ Form::close() }}
               </div>
            </div>
            <div class="row row-sm-offset-3">
               <div class="col-xs-12">
                  <div class="col-xs-12 col-sm-6">
                     <label class="checkbox">
                     <input type="checkbox" value="remember-me">Remember Me
                     </label>
                  </div>
                  <div class="col-xs-12 col-sm-6">
                     <p class="forgotPassword">
                        <a href="#" data-toggle="modal" data-target="#forgotPasswordEmail"> @lang('app.forgot_password')</a>
                     </p>
                  </div>
               </div>
            </div>
            <p class="new_register">Are you an agent wanting to join the platform?&nbsp;<a href="{{ route('user.create') }}">Register</a></p>
         </div>
      </div>
   </div>
</div>
<div class="modal fade" id="forgotPasswordEmail" tabindex="-1" role="dialog">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         {!! Form::open(['route'=>'send_reset_link']) !!}
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">@lang('app.enter_email_to_reset_password')</h4>
         </div>
         <div class="modal-body">
            <div class="form-group">
               <label for="email" class="control-label">@lang('app.email'):</label>
               <input type="text" class="form-control" id="email" name="email">
               <div id="email_info"></div>
            </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">@lang('app.close')</button>
            <button type="submit" class="btn btn-primary" id="send_reset_link">@lang('app.send_reset_link')</button>
         </div>
         </form>
      </div>
   </div>
</div>
@endsection
@section('page-js')
<script>
   var options = {closeButton : true};
   @if(session('error'))
       toastr.error('{{ session('error') }}', 'Error!', options)
   @endif
</script>
@endsection

resources/views/theme/single_page.blade.php
@extends('layout.main')
@section('title') @if( ! empty($title)) {{ $title }} | @endif @parent @endsection
@section('main')
<!-- <div class="jumbotron jumbotron-xs">
   <div class="container">
       <div class="row">
           <div class="col-sm-12 col-lg-12">
               <h2>{{ $page->title }}</h2>
           </div>
       </div>
   </div>
   </div> -->
<div class="row mlr0">
   <div class="page_wrapper page-{{ $page->id }}">
    
      {!! $page->post_content !!}         
   </div>
</div>
@endsection
@section('page-js')
<script>
   @if(session('success'))
       toastr.success('{{ session('success') }}', '<?php echo trans('app.success') ?>', toastr_options);
   @endif
</script>
@endsection